In [23]:
import polars as pl

In [1]:
import nflreadpy as nfl

In [2]:
player_stats = nfl.load_player_stats(seasons=[2025])

In [3]:
player_stats.head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 25.66     ┆ 25.66     │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002615 ┆ J.Flacco  ┆ Joe       ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.2      ┆ 12.2      │
│ 8         ┆           ┆ Flacco    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
player_stats.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'season',
 'week',
 'season_type',
 'game_id',
 'team',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'pacr',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'def_punt_blocks',
 'def_pat_blocks',
 'def_fg_blocks',
 'def_2pt_atts',
 'def_2pt_made',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'fumbles_forced_by_opp',
 'fumbles_not_forced',
 'fumbles_out_of_bounds',
 'fumbles_total',
 'fumbles_lost_total',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pt_att',
 'pt_blocked',
 'pt_long',
 'pt_yards',
 'pt_inside_20',
 'pt_out_of_bounds',
 'pt_downed',
 'pt_touchback',
 'pt_fair_caught',
 'pt_returned',
 'pt_return_yards',
 'pt_return_tds',
 'pt_net_yards',
 'fantasy_points',
 'fantasy_points_ppr']

In [7]:
goff_stats = player_stats.filter(
    player_stats["player_display_name"] == "Jared Goff"
)

In [8]:
goff_stats

shape: (17, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 10.9      ┆ 10.9      │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 33.96     ┆ 33.96     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.68     ┆ 12.68     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.72     ┆ 12.72     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 20.12     ┆ 20.12     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 16.16     ┆ 16.16     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 25.52     ┆ 25.52     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 26.46     ┆ 26.46     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 2.08      ┆ 2.08      │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 15.24     ┆ 15.24     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
type(player_stats)

polars.dataframe.frame.DataFrame

In [12]:
goff_passing = goff_stats.select([
    "week",
    "opponent_team",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions"
])

In [13]:
goff_passing

shape: (17, 7)
┌──────┬───────────────┬─────────────┬──────────┬───────────────┬─────────────┬────────────────────┐
│ week ┆ opponent_team ┆ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ passing_intercepti │
│ ---  ┆ ---           ┆ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ons                │
│ i32  ┆ str           ┆ i32         ┆ i32      ┆ i32           ┆ i32         ┆ ---                │
│      ┆               ┆             ┆          ┆               ┆             ┆ i32                │
╞══════╪═══════════════╪═════════════╪══════════╪═══════════════╪═════════════╪════════════════════╡
│ 1    ┆ GB            ┆ 31          ┆ 39       ┆ 225           ┆ 1           ┆ 1                  │
│ 2    ┆ CHI           ┆ 23          ┆ 28       ┆ 334           ┆ 5           ┆ 0                  │
│ 3    ┆ BAL           ┆ 20          ┆ 28       ┆ 202           ┆ 1           ┆ 0                  │
│ 4    ┆ CLE           ┆ 16          ┆ 27       ┆ 168           ┆ 2           ┆ 1                  │
│ 5    ┆ CIN           ┆ 19          ┆ 23       ┆ 258           ┆ 3           ┆ 0                  │
│ …    ┆ …             ┆ …           ┆ …        ┆ …             ┆ …           ┆ …                  │
│ 14   ┆ DAL           ┆ 25          ┆ 34       ┆ 309           ┆ 1           ┆ 0                  │
│ 15   ┆ LA            ┆ 25          ┆ 41       ┆ 338           ┆ 3           ┆ 0                  │
│ 16   ┆ PIT           ┆ 34          ┆ 54       ┆ 364           ┆ 3           ┆ 0                  │
│ 17   ┆ MIN           ┆ 18          ┆ 29       ┆ 197           ┆ 1           ┆ 2                  │
│ 18   ┆ CHI           ┆ 27          ┆ 42       ┆ 331           ┆ 1           ┆ 1                  │
└──────┴───────────────┴─────────────┴──────────┴───────────────┴─────────────┴────────────────────┘

In [14]:
goff_passing = goff_passing.with_columns(
    (
        (goff_passing["completions"] / goff_passing["attempts"]) * 100
    ).round(2).alias("completion_percentage")
)

In [19]:
(
    (goff_passing["completions"] / goff_passing["attempts"]) * 100
).round(2)

shape: (17,)
Series: 'completions' [f64]
[
	79.49
	82.14
	71.43
	59.26
	82.61
	…
	73.53
	60.98
	62.96
	62.07
	64.29
]

In [20]:
goff_passing = goff_passing.with_columns(
    (
        (goff_passing["completions"] / goff_passing["attempts"]) * 100
    ).round(2).alias("completion_percentage")
)

In [21]:
goff_passing

shape: (17, 8)
┌──────┬─────────────┬─────────────┬──────────┬─────────────┬────────────┬────────────┬────────────┐
│ week ┆ opponent_te ┆ completions ┆ attempts ┆ passing_yar ┆ passing_td ┆ passing_in ┆ completion │
│ ---  ┆ am          ┆ ---         ┆ ---      ┆ ds          ┆ s          ┆ terception ┆ _percentag │
│ i32  ┆ ---         ┆ i32         ┆ i32      ┆ ---         ┆ ---        ┆ s          ┆ e          │
│      ┆ str         ┆             ┆          ┆ i32         ┆ i32        ┆ ---        ┆ ---        │
│      ┆             ┆             ┆          ┆             ┆            ┆ i32        ┆ f64        │
╞══════╪═════════════╪═════════════╪══════════╪═════════════╪════════════╪════════════╪════════════╡
│ 1    ┆ GB          ┆ 31          ┆ 39       ┆ 225         ┆ 1          ┆ 1          ┆ 79.49      │
│ 2    ┆ CHI         ┆ 23          ┆ 28       ┆ 334         ┆ 5          ┆ 0          ┆ 82.14      │
│ 3    ┆ BAL         ┆ 20          ┆ 28       ┆ 202         ┆ 1          ┆ 0          ┆ 71.43      │
│ 4    ┆ CLE         ┆ 16          ┆ 27       ┆ 168         ┆ 2          ┆ 1          ┆ 59.26      │
│ 5    ┆ CIN         ┆ 19          ┆ 23       ┆ 258         ┆ 3          ┆ 0          ┆ 82.61      │
│ …    ┆ …           ┆ …           ┆ …        ┆ …           ┆ …          ┆ …          ┆ …          │
│ 14   ┆ DAL         ┆ 25          ┆ 34       ┆ 309         ┆ 1          ┆ 0          ┆ 73.53      │
│ 15   ┆ LA          ┆ 25          ┆ 41       ┆ 338         ┆ 3          ┆ 0          ┆ 60.98      │
│ 16   ┆ PIT         ┆ 34          ┆ 54       ┆ 364         ┆ 3          ┆ 0          ┆ 62.96      │
│ 17   ┆ MIN         ┆ 18          ┆ 29       ┆ 197         ┆ 1          ┆ 2          ┆ 62.07      │
│ 18   ┆ CHI         ┆ 27          ┆ 42       ┆ 331         ┆ 1          ┆ 1          ┆ 64.29      │
└──────┴─────────────┴─────────────┴──────────┴─────────────┴────────────┴────────────┴────────────┘

In [25]:
goff_season = goff_passing.select([
    pl.col("completions").sum().alias("completions"),
    pl.col("attempts").sum().alias("attempts"),
    pl.col("passing_yards").sum().alias("passing_yards"),
    pl.col("passing_tds").sum().alias("passing_tds"),
    pl.col("passing_interceptions").sum().alias("interceptions")
])

In [27]:
goff_season

shape: (1, 5)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╡
│ 393         ┆ 578      ┆ 4564          ┆ 34          ┆ 8             │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┘

In [28]:
goff_season = goff_season.with_columns(
    (
        (pl.col("completions") / pl.col("attempts")) * 100
    ).round(2).alias("completion_percentage")
)

In [29]:
goff_season

shape: (1, 6)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┬───────────────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions ┆ completion_percentage │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           ┆ ---                   │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           ┆ f64                   │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╪═══════════════════════╡
│ 393         ┆ 578      ┆ 4564          ┆ 34          ┆ 8             ┆ 67.99                 │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┴───────────────────────┘

In [32]:
player_name = "Josh Allen"

selected_player = player_stats.filter(
    pl.col("player_display_name") == player_name
)

In [33]:
selected_player

shape: (18, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 38.76     ┆ 38.76     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 11.82     ┆ 11.82     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 23.02     ┆ 23.02     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 24.86     ┆ 24.86     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 19.42     ┆ 19.42     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 24.52     ┆ 24.52     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 6.9       ┆ 6.9       │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 23.18     ┆ 23.18     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 30.22     ┆ 30.22     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 21.92     ┆ 21.92     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [34]:
def get_player_stats(player_name):
    selected_player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    return selected_player

In [35]:
get_player_stats("Jared Goff")

shape: (17, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 10.9      ┆ 10.9      │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 33.96     ┆ 33.96     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.68     ┆ 12.68     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.72     ┆ 12.72     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 20.12     ┆ 20.12     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 16.16     ┆ 16.16     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 25.52     ┆ 25.52     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 26.46     ┆ 26.46     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 2.08      ┆ 2.08      │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003310 ┆ J.Goff    ┆ Jared     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 15.24     ┆ 15.24     │
│ 6         ┆           ┆ Goff      ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [36]:
get_player_stats("Josh Allen")

shape: (18, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 38.76     ┆ 38.76     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 11.82     ┆ 11.82     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 23.02     ┆ 23.02     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 24.86     ┆ 24.86     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 19.42     ┆ 19.42     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 24.52     ┆ 24.52     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 6.9       ┆ 6.9       │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 23.18     ┆ 23.18     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 30.22     ┆ 30.22     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ J.Allen   ┆ Josh      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 21.92     ┆ 21.92     │
│ 7         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
def get_player_info(player_name):
    player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    player_info = player.select([
        "player_id",
        "player_display_name",
        "position",
        "headshot_url",
        "team"
    ]).unique()

    return player_info

In [38]:
get_player_info("Jared Goff")

shape: (1, 5)
┌────────────┬─────────────────────┬──────────┬─────────────────────────────────┬──────┐
│ player_id  ┆ player_display_name ┆ position ┆ headshot_url                    ┆ team │
│ ---        ┆ ---                 ┆ ---      ┆ ---                             ┆ ---  │
│ str        ┆ str                 ┆ str      ┆ str                             ┆ str  │
╞════════════╪═════════════════════╪══════════╪═════════════════════════════════╪══════╡
│ 00-0033106 ┆ Jared Goff          ┆ QB       ┆ https://static.www.nfl.com/ima… ┆ DET  │
└────────────┴─────────────────────┴──────────┴─────────────────────────────────┴──────┘

In [39]:
get_player_info("Josh Allen")

shape: (1, 5)
┌────────────┬─────────────────────┬──────────┬─────────────────────────────────┬──────┐
│ player_id  ┆ player_display_name ┆ position ┆ headshot_url                    ┆ team │
│ ---        ┆ ---                 ┆ ---      ┆ ---                             ┆ ---  │
│ str        ┆ str                 ┆ str      ┆ str                             ┆ str  │
╞════════════╪═════════════════════╪══════════╪═════════════════════════════════╪══════╡
│ 00-0034857 ┆ Josh Allen          ┆ QB       ┆ https://static.www.nfl.com/ima… ┆ BUF  │
└────────────┴─────────────────────┴──────────┴─────────────────────────────────┴──────┘

In [40]:
def get_qb_season_stats(player_name):
    player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    season_stats = player.select([
        pl.col("completions").sum().alias("completions"),
        pl.col("attempts").sum().alias("attempts"),
        pl.col("passing_yards").sum().alias("passing_yards"),
        pl.col("passing_tds").sum().alias("passing_tds"),
        pl.col("passing_interceptions").sum().alias("interceptions")
    ])

    season_stats = season_stats.with_columns(
        (
            (pl.col("completions") / pl.col("attempts")) * 100
        ).round(2).alias("completion_percentage")
    )

    return season_stats

In [41]:
get_qb_season_stats("Jared Goff")

shape: (1, 6)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┬───────────────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions ┆ completion_percentage │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           ┆ ---                   │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           ┆ f64                   │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╪═══════════════════════╡
│ 393         ┆ 578      ┆ 4564          ┆ 34          ┆ 8             ┆ 67.99                 │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┴───────────────────────┘

In [42]:
get_qb_season_stats("Josh Allen")

shape: (1, 6)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┬───────────────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions ┆ completion_percentage │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           ┆ ---                   │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           ┆ f64                   │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╪═══════════════════════╡
│ 372         ┆ 534      ┆ 4224          ┆ 29          ┆ 12            ┆ 69.66                 │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┴───────────────────────┘

In [43]:
[
    column
    for column in player_stats.columns
    if "rush" in column
]

['rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40']

In [44]:
[
    column
    for column in player_stats.columns
    if "carr" in column
]

['carries']

In [52]:
def get_rb_season_stats(player_name):
    player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    season_stats = player.select([
        # Rushing
        pl.col("carries").sum().alias("carries"),
        pl.col("rushing_yards").sum().alias("rushing_yards"),
        pl.col("rushing_tds").sum().alias("rushing_tds"),
        pl.col("rushing_first_downs").sum().alias("rushing_first_downs"),
        pl.col("rushing_fumbles").sum().alias("rushing_fumbles"),

        # Receiving
        pl.col("targets").sum().alias("targets"),
        pl.col("receptions").sum().alias("receptions"),
        pl.col("receiving_yards").sum().alias("receiving_yards"),
        pl.col("receiving_tds").sum().alias("receiving_tds")
    ])

    season_stats = season_stats.with_columns([
        (
            pl.col("rushing_yards") / pl.col("carries")
        ).round(2).alias("yards_per_carry"),

        (
            pl.col("receiving_yards") / pl.col("receptions")
        ).round(2).alias("yards_per_reception")
    ])

    return season_stats

In [53]:
get_rb_season_stats("Jahmyr Gibbs")

shape: (1, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ carries ┆ rushing_ya ┆ rushing_t ┆ rushing_f ┆ … ┆ receiving ┆ receiving ┆ yards_per ┆ yards_per │
│ ---     ┆ rds        ┆ ds        ┆ irst_down ┆   ┆ _yards    ┆ _tds      ┆ _carry    ┆ _receptio │
│ i32     ┆ ---        ┆ ---       ┆ s         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ n         │
│         ┆ i32        ┆ i32       ┆ ---       ┆   ┆ i32       ┆ i32       ┆ f64       ┆ ---       │
│         ┆            ┆           ┆ i32       ┆   ┆           ┆           ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 243     ┆ 1223       ┆ 13        ┆ 56        ┆ … ┆ 616       ┆ 5         ┆ 5.03      ┆ 8.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [54]:
[
    column
    for column in player_stats.columns
    if "receiv" in column
]

['receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40']

In [55]:
[
    column
    for column in player_stats.columns
    if "target" in column or "reception" in column
]

['receptions', 'targets', 'target_share']

In [67]:
def get_player_season_stats(player_name):
    player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    if player.is_empty():
        return "Player not found"

    position = player["position"][0]

    if position == "QB":
        return get_qb_season_stats(player_name)

    elif position == "RB":
        return get_rb_season_stats(player_name)

    elif position == "WR":
        return get_wr_season_stats(player_name)


    else:
        return f"Stats for position {position} are not built yet."

In [57]:
get_player_season_stats("Jared Goff")

shape: (1, 6)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┬───────────────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions ┆ completion_percentage │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           ┆ ---                   │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           ┆ f64                   │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╪═══════════════════════╡
│ 393         ┆ 578      ┆ 4564          ┆ 34          ┆ 8             ┆ 67.99                 │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┴───────────────────────┘

In [58]:
get_player_season_stats("Jahmyr Gibbs")

shape: (1, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ carries ┆ rushing_ya ┆ rushing_t ┆ rushing_f ┆ … ┆ receiving ┆ receiving ┆ yards_per ┆ yards_per │
│ ---     ┆ rds        ┆ ds        ┆ irst_down ┆   ┆ _yards    ┆ _tds      ┆ _carry    ┆ _receptio │
│ i32     ┆ ---        ┆ ---       ┆ s         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ n         │
│         ┆ i32        ┆ i32       ┆ ---       ┆   ┆ i32       ┆ i32       ┆ f64       ┆ ---       │
│         ┆            ┆           ┆ i32       ┆   ┆           ┆           ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 243     ┆ 1223       ┆ 13        ┆ 56        ┆ … ┆ 616       ┆ 5         ┆ 5.03      ┆ 8.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [61]:
get_player_season_stats("Amon-Ra St. Brown")

'Stats for position WR are not built yet.'

In [60]:
player_stats.filter(
    pl.col("player_display_name").str.contains("Amon")
).select([
    "player_display_name",
    "position",
    "team"
]).unique()

shape: (1, 3)
┌─────────────────────┬──────────┬──────┐
│ player_display_name ┆ position ┆ team │
│ ---                 ┆ ---      ┆ ---  │
│ str                 ┆ str      ┆ str  │
╞═════════════════════╪══════════╪══════╡
│ Amon-Ra St. Brown   ┆ WR       ┆ DET  │
└─────────────────────┴──────────┴──────┘

In [62]:
def get_wr_season_stats(player_name):
    player = player_stats.filter(
        pl.col("player_display_name") == player_name
    )

    season_stats = player.select([
        pl.col("targets").sum().alias("targets"),
        pl.col("receptions").sum().alias("receptions"),
        pl.col("receiving_yards").sum().alias("receiving_yards"),
        pl.col("receiving_tds").sum().alias("receiving_tds"),
        pl.col("receiving_first_downs").sum().alias("receiving_first_downs"),
        pl.col("receiving_fumbles").sum().alias("receiving_fumbles")
    ])

    season_stats = season_stats.with_columns(
        (
            pl.col("receiving_yards") / pl.col("receptions")
        ).round(2).alias("yards_per_reception")
    )

    return season_stats

In [63]:
get_wr_season_stats("Amon-Ra St. Brown")

shape: (1, 7)
┌─────────┬────────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ targets ┆ receptions ┆ receiving_yar ┆ receiving_td ┆ receiving_fi ┆ receiving_fu ┆ yards_per_re │
│ ---     ┆ ---        ┆ ds            ┆ s            ┆ rst_downs    ┆ mbles        ┆ ception      │
│ i32     ┆ i32        ┆ ---           ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│         ┆            ┆ i32           ┆ i32          ┆ i32          ┆ i32          ┆ f64          │
╞═════════╪════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 172     ┆ 117        ┆ 1401          ┆ 11           ┆ 71           ┆ 1            ┆ 11.97        │
└─────────┴────────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [64]:
get_player_season_stats("Jared Goff")

shape: (1, 6)
┌─────────────┬──────────┬───────────────┬─────────────┬───────────────┬───────────────────────┐
│ completions ┆ attempts ┆ passing_yards ┆ passing_tds ┆ interceptions ┆ completion_percentage │
│ ---         ┆ ---      ┆ ---           ┆ ---         ┆ ---           ┆ ---                   │
│ i32         ┆ i32      ┆ i32           ┆ i32         ┆ i32           ┆ f64                   │
╞═════════════╪══════════╪═══════════════╪═════════════╪═══════════════╪═══════════════════════╡
│ 393         ┆ 578      ┆ 4564          ┆ 34          ┆ 8             ┆ 67.99                 │
└─────────────┴──────────┴───────────────┴─────────────┴───────────────┴───────────────────────┘

In [65]:
get_player_season_stats("Jahmyr Gibbs")

shape: (1, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ carries ┆ rushing_ya ┆ rushing_t ┆ rushing_f ┆ … ┆ receiving ┆ receiving ┆ yards_per ┆ yards_per │
│ ---     ┆ rds        ┆ ds        ┆ irst_down ┆   ┆ _yards    ┆ _tds      ┆ _carry    ┆ _receptio │
│ i32     ┆ ---        ┆ ---       ┆ s         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ n         │
│         ┆ i32        ┆ i32       ┆ ---       ┆   ┆ i32       ┆ i32       ┆ f64       ┆ ---       │
│         ┆            ┆           ┆ i32       ┆   ┆           ┆           ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 243     ┆ 1223       ┆ 13        ┆ 56        ┆ … ┆ 616       ┆ 5         ┆ 5.03      ┆ 8.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [68]:
get_player_season_stats("Amon-Ra St. Brown")

shape: (1, 7)
┌─────────┬────────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ targets ┆ receptions ┆ receiving_yar ┆ receiving_td ┆ receiving_fi ┆ receiving_fu ┆ yards_per_re │
│ ---     ┆ ---        ┆ ds            ┆ s            ┆ rst_downs    ┆ mbles        ┆ ception      │
│ i32     ┆ i32        ┆ ---           ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│         ┆            ┆ i32           ┆ i32          ┆ i32          ┆ i32          ┆ f64          │
╞═════════╪════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 172     ┆ 117        ┆ 1401          ┆ 11           ┆ 71           ┆ 1            ┆ 11.97        │
└─────────┴────────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┘